In [6]:
print("hello")

hello


In [24]:
#To create Rank 1  Array
import numpy as np
#l=[10,20,30,40,50]
an_array=np.array([[10,20,30,],[40,50,60],[70,80,90]]) #an_array is numpy array
an_array[0,0]=444
print(an_array)

#an_array.shape

#type(an_array)
#print(an_array[0])

[[444  20  30]
 [ 40  50  60]
 [ 70  80  90]]


In [25]:
import numpy as np
#create a 2X2 array of zeros
ex1=np.zeros((100,100))
print(ex1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [26]:
#create an array of ones
ex4=np.ones((3,3))
print(ex4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [29]:
#create a 2x2 matrix with the diagonal  is and the others 0
ex3 = np.eye(4,4)
print(ex3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
#create a 2x2 matrix filled with 9.0
ex2=np.full((2,2),(9.0))
print(ex2)

[[9. 9.]
 [9. 9.]]


In [32]:
#create an array of random floats between 0 and 1
ex5=np.random.random( (4,3) )
print(ex5)

[[0.92223856 0.49486569 0.56307254]
 [0.97778405 0.99870736 0.17631592]
 [0.73146717 0.54442497 0.1421499 ]
 [0.82559581 0.62478339 0.16823657]]


In [34]:
#arange function pronounciation => 'a-range'
import numpy as np
an_array=np.arange(10)
an_array=np.arange(2,11,2)
print(an_array)


[ 2  4  6  8 10]


In [36]:
#reshape an array
import numpy as np
an_array=np.arange(9)
an_array=an_array.reshape((3,3)) #here reshape of array of 3x3(2d-array)
an_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
import numpy as np
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
a_slice=an_array[1:3,2:4]
a_slice
an_array

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [14]:
import numpy as np
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
a_slice=an_array[1:3,2:4]
a_slice[0,0]=0
print(a_slice)
print(an_array)

[[ 0 24]
 [33 34]]
[[11 12 13 14]
 [21 22  0 24]
 [31 32 33 34]]


In [13]:
import numpy as np
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
a_slice=an_array[1:3,2:4].copy()
a_slice[0,0]=0
print(an_array)
print(a_slice)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
[[ 0 24]
 [33 34]]


In [17]:
import numpy as np
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
a_slice=an_array[1:3][1:4] #using 2 brackets there will be slice of slice
a_slice
print(a_slice)
#print(an_array)

[[31 32 33 34]]


In [18]:
#Boolean Index
#create a 3x2 array
an_array=np.array([[11,12],[21,22],[31,32]])


filter=an_array>25
print(filter)

[[False False]
 [False False]
 [ True  True]]


In [22]:
#Boolean Index
#create a 3x2 array
an_array=np.array([[11,12],[21,22],[31,32]])


filter=an_array%2==0 #without using loop
print(filter)

[[False  True]
 [False  True]
 [False  True]]


In [23]:
#Boolean Index
#create a 3x2 array
an_array=np.array([[11,12],[21,22],[31,32]])


filter=an_array%2==0 #without using loop
print(an_array[filter])#only true data is printed and printed only in 1-d array

[12 22 32]


In [25]:
#Boolean Index
#create a 3x2 array
an_array=np.array([[11,12],[21,22],[31,32]])


filter=an_array%2!=0 #without using loop
print(an_array[filter])

[11 21 31]


In [27]:
#Boolean Index
#create a 3x2 array
an_array=np.array([[11,12],[21,22],[31,32]])
fil1=an_array>20
fil2=an_array<30
filter=fil1&fil2
print(an_array[filter])

[21 22]


#Arithmatic operation

